name: demo

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  make-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: pip install -e .
      - name: make demo
        run: make demo

